#ifndef CONFIG_H
#define CONFIG_H

#define FREQUENCY_FURNACE 5
#define FREQUENCY_WIDEFOV 8
#define FREQUENCY_NARROWFOV 12

// Modbus config options
#define TRIG_NUM_COIL 8
#define TRIG_NUM_INP 8
#define TRIG_NUM_HOLD 8


// Modbus addresses
#define TRIG_ENABLE_COIL 0
#define TRIG_VAL_UPDATED_COIL 1
#define TRIG_FURNACE_ENABLE_COIL 2
#define TRIG_WIDEFOV_ENABLE_COIL 3
#define TRIG_NARROWFOV_ENABLE_COIL 4

#define TRIG_INPUT_START 30001

#define TRIG_FURNACE_INTVL_HOLD 40001
#define TRIG_WIDEFOV_INTVL_HOLD 40003
#define TRIG_NARROWFOV_INTVL_HOLD 40005

#endif